/* date = March 28th 2023 9:25 pm */

#ifndef OBJECT_H
#define OBJECT_H

#include "types.h"

enum ObjectType {
    OBJECT_TYPE_GALAXY,
    OBJECT_TYPE_OPEN_STAR_CLUSTER,
    OBJECT_TYPE_GLOBULAR_STAR_CLUSTER,
    OBJECT_TYPE_REFLECTION_NEBULA,
    OBJECT_TYPE_PLANETARY_NEBULA,
    OBJECT_TYPE_CLUSTER,
    OBJECT_TYPE_ASTERISM,
    OBJECT_TYPE_KNOT,
    OBJECT_TYPE_TRIPLE_STAR,
    OBJECT_TYPE_DOUBLE_STAR,
    OBJECT_TYPE_SINGLE_STAR,
    OBJECT_TYPE_UNCERTAIN,
    OBJECT_TYPE_UNIDENTIFIED,
    OBJECT_TYPE_PHOTOGRAPHIC_PLATE_DEFECT,
    OBJECT_TYPE_NONEXISTENT,
    OBJECT_TYPE_PLANET,
    OBJECT_TYPE_COUNT
};

#endif //OBJECT_H
